version: '2'
services:
  hubot:
    extends:
      file: common-services.yml
      service: app
    mem_limit: 512m
    env_file:
      - '.env'
    depends_on:
      - redis
  redis:
    image: redis:3.2
